### ISSUE TITLE
Make ragdoll time configurable

### ISSUE THREAD

**Issue by loganlearner** [CFC-Servers/cfc_yeeting#4]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/ulx_yeet/sh_yeet.lua#L187-L189

It would be preferred to have players not forced to wait 30 seconds to unragdoll after yeeting. So having a way for the admin to choose how long they will be ragdolled for would be preferable.

**Comment by wrefgtzweve** [comment]
that's a safeguard

**Comment by loganlearner** [comment]
Yeah, I understand that I want it to be a configured time frame because an admin can hold the yeeted player for the 30 seconds to be annoying...

**Comment by wrefgtzweve** [comment]
oh yeah that's fair, i can implement that

**Comment by plally** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/ulx_yeet/sh_yeet.lua#L187-L189

**Comment by plally** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/main/lua/autorun/ulx_yeet.lua#L2-L4

**Comment by plally** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/autorun/ulx_yeet.lua#L2-L4

**Comment by wrefgtzweve** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/ulx_yeet/sh_yeet.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L208

**Comment by plally** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/autorun/ulx_yeet.lua#L2-L4

**Comment by wrefgtzweve** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/ulx_yeet/sh_yeet.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L206-L210

**Comment by plally** [comment]
https://github.com/CFC-Servers/cfc_yeeting/blob/1bc69e5ad35b7070a5f5b05d0a8e20c5ddf1d8c5/lua/ulx_yeet/sh_yeet.lua#L49-L56
